package com.auction.flab.application.exception;

public enum ErrorCode {

    EXCEPTION_ON_EXTRACT_FIELD_VALUE,
    EXCEPTION_ON_INPUT_PROJECT,
    EXCEPTION_ON_INPUT_MEMBER,
    EXCEPTION_ON_LOGIN,
    EXCEPTION_ON_TOKEN_VALIDATION,
    EXCEPTION_ON_UPDATE_PROJECT,
    EXCEPTION_ON_DELETE_PROJECT,
    EXCEPTION_ON_NOT_FOUND,
    EXCEPTION_ON_INPUT_PROJECT_APPLICANT,
    EXCEPTION_ON_ALREADY_CONFIRM;

}
